name: Push Docker image

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username mtt42 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/mtt42/hello-world-ghcr:test
          docker push ghcr.io/mtt42/hello-world-ghcr:test

