# This is a basic workflow to help you get started with Actions

name: Basic CI

on:
  push:  
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip list
